version: '3'

services:
  postgres:
    container_name: biblioteca-postgres
    image: postgres
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - postgres-biblioteca-network

  pgadmin:
    container_name: biblioteca-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gajigo.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres-biblioteca-network

networks:
  postgres-biblioteca-network:
    driver: bridge